"""
UFO/UAP Research System
========================
Uses the GitHub Copilot SDK to programmatically research https://www.war.gov/ufo/
and generate a fact-checked report that includes image analysis.

Usage:
    pip install github-copilot-sdk
    python research.py

Authentication (choose one):
    - Sign in to GitHub Copilot CLI beforehand (recommended)
    - Set COPILOT_GITHUB_TOKEN / GH_TOKEN / GITHUB_TOKEN env variable
    - Use BYOK: set BYOK_PROVIDER, BYOK_API_KEY, BYOK_MODEL env variables

Reports are written to the ./reports/ directory as Markdown files.
"""

import asyncio
import os
from datetime import datetime, timezone
from pathlib import Path

from copilot import CopilotClient, SubprocessConfig
from copilot.generated.session_events import AssistantMessageData, SessionIdleData
from copilot.session import PermissionHandler

# ---------------------------------------------------------------------------
# Target URL
# ---------------------------------------------------------------------------
TARGET_URL = "https://www.war.gov/ufo/"

# ---------------------------------------------------------------------------
# Research prompt sent to the Copilot agent
# ---------------------------------------------------------------------------
RESEARCH_PROMPT = f"""You are a research analyst. Produce a thorough, fact-checked Markdown report
on the official US government UAP (Unidentified Anomalous Phenomena) portal NOW.
Do NOT ask clarifying questions. Proceed immediately with the best available information.

Primary target: {TARGET_URL}

**Instructions (execute all steps without waiting for confirmation):**

1. **Browse** – Attempt to fetch {TARGET_URL} and linked sub-pages.
   If unreachable, search the web for the following and use whatever you can access:
   - "war.gov/ufo declassified UAP 2026 PURSUE release"
   - https://www.aaro.mil/
   - https://science.nasa.gov/uap/
   - News coverage from AP, Reuters, NYT, USA Today on the May 2026 DoW PURSUE release.
   Use every available source; do not stop because one URL is blocked.

2. **Document inventory** – List every document, report, video, and image found,
   including title, date, originating agency, and a brief description.

3. **Image analysis & fact-checking** – For every image or photograph:
   - Describe what is depicted.
   - Note official caption, date, and source agency.
   - Cross-reference for credibility; flag inconsistencies.

4. **Key claims analysis** – For each major factual claim:
   - Quote the claim exactly.
   - Assess supporting evidence.
   - Note counter-evidence or expert disagreement.
   - Rate: Verified / Plausible / Unverified / Contested.

5. **Write the complete Markdown report now** with these exact sections:

# UFO/UAP Research Report
## Executive Summary
## Site Overview
## Document Inventory
## Image Analysis & Fact-Check
## Key Claims & Credibility Ratings
## Overall Credibility Assessment
## Sources & References
## Research Metadata

Write the full report immediately. Be precise, cite specific sources, neutral tone.
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_client() -> CopilotClient:
    """Return a configured CopilotClient, honouring BYOK env vars when set."""
    github_token = (
        os.environ.get("COPILOT_GITHUB_TOKEN")
        or os.environ.get("GITHUB_COPILOT_API_TOKEN")
        or os.environ.get("GH_TOKEN")
        or os.environ.get("GITHUB_TOKEN")
    )

    config = SubprocessConfig(
        github_token=github_token or None,
    )
    return CopilotClient(config)


def _resolve_model() -> str:
    """Return the model name, preferring the COPILOT_MODEL env override."""
    return os.environ.get("COPILOT_MODEL", "gpt-4.1")


def _save_report(content: str, reports_dir: Path) -> Path:
    """Write the final report to a timestamped Markdown file."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%SZ")
    report_path = reports_dir / f"ufo_research_report_{timestamp}.md"

    header = (
        "# UFO/UAP Research Report\n\n"
        f"*Generated by:* GitHub Copilot SDK  \n"
        f"*Source:* {TARGET_URL}  \n"
        f"*Date:* {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}  \n\n"
        "---\n\n"
    )

    # Only prepend the header if the model didn't already start with a heading
    body = content.strip()
    if not body.startswith("#"):
        body = header + body

    report_path.write_text(body, encoding="utf-8")
    return report_path


# ---------------------------------------------------------------------------
# Core research coroutine
# ---------------------------------------------------------------------------

async def run_research(reports_dir: Path = Path("reports")) -> Path:
    """Execute the research session and return the path of the saved report."""
    model = _resolve_model()

    print("=" * 60)
    print("  UFO/UAP Research System – GitHub Copilot SDK")
    print("=" * 60)
    print(f"  Target : {TARGET_URL}")
    print(f"  Model  : {model}")
    print(f"  Time   : {datetime.now(tz=timezone.utc).isoformat()}")
    print("=" * 60)
    print()

    message_parts: list[str] = []

    async with _build_client() as client:
        print("[*] Copilot client connected. Creating research session …\n")

        async with await client.create_session(
            on_permission_request=PermissionHandler.approve_all,
            model=model,
        ) as session:

            idle_event = asyncio.Event()

            def on_event(event) -> None:
                match event.data:
                    case AssistantMessageData() as data:
                        print(data.content, end="", flush=True)
                        message_parts.append(data.content)
                    case SessionIdleData():
                        idle_event.set()

            session.on(on_event)

            print("[*] Sending research prompt …\n")
            await session.send(RESEARCH_PROMPT)
            await idle_event.wait()

            # If the agent asked a clarifying question instead of writing the report,
            # push it to proceed immediately with what it knows.
            first_response = "".join(message_parts)
            short_or_question = (
                "?" in first_response[-500:]
                or "would you like" in first_response[-500:].lower()
                or len(first_response.strip()) < 500
            )
            if short_or_question:
                idle_event.clear()
                print("\n[*] Agent asked for confirmation — pushing to proceed …\n")
                await session.send(
                    "Do not ask any more questions. Write the complete Markdown report "
                    "right now using all knowledge you have about the US government UAP "
                    "disclosures, the war.gov/ufo portal, the May 2026 PURSUE release, "
                    "AARO, and NASA UAP findings. Include all required sections."
                )
                await idle_event.wait()

    print("\n\n[*] Research complete. Saving report …")
    report_path = _save_report("".join(message_parts), reports_dir)
    print(f"[+] Report saved → {report_path}")
    return report_path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    report_path = asyncio.run(run_research())
    print(f"\nDone. Open your report at: {report_path}\n")


if __name__ == "__main__":
    main()
